samples:    
    Manthiram_T101_S40: Manthiram_T101_S40
    Manthiram_T103_S41: Manthiram_T103_S41
    Manthiram_T10_S39: Manthiram_T10_S39
    Manthiram_T126_S42: Manthiram_T126_S42
    Manthiram_T133_S43: Manthiram_T133_S43
    Manthiram_T22_S44: Manthiram_T22_S44
    Manthiram_T70_S45: Manthiram_T70_S45
    CNMC_T109_S2: CNMC_T109_S2
    CNMC_T124_S3: CNMC_T124_S3
    CNMC_T125_S4: CNMC_T125_S4
    CNMC_T50_S1: CNMC_T50_S1
